type User @table {
  email: String!
  role: String!
  displayName: String
  avatarUrl: String
}

type Feature @table {
  title: String!
  description: String!
  status: String!
  releaseDate: Date
}

type BugReport @table {
  title: String!
  description: String!
  severity: String!
  status: String!
  screenshotUrl: String
  reproductionSteps: String
  reporter: User
  feature: Feature
}

type Feedback @table {
  content: String!
  createdAt: Timestamp!
  rating: Int
  user: User
  feature: Feature
}

type Assignment @table {
  assignedAt: Timestamp!
  developer: User
  bugReport: BugReport
}